package de.dennis.mobilesensing_module.mobilesensing.Storage;

import java.util.ArrayList;
import java.util.List;

import io.objectbox.annotation.Backlink;
import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Relation;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.BoxStore;
import io.objectbox.relation.ToMany;
import io.objectbox.relation.ToOne;

/**
 * Created by Dennis on 04.08.2017.
 */

@Entity
public class SensorValue {
    @Id
    private long timestamp;
    @Backlink
    private List<StringEntitiy> values = new ToMany<>(this, SensorValue_.values);

    @Relation
    private SensorTimeseries sensor_timeseries;
    /** Used to resolve relations */
    @Internal
    @Generated(1307364262)
    transient BoxStore __boxStore;
    @Internal
    @Generated(1539810802)
    transient ToOne<SensorTimeseries> sensor_timeseriesToOne = new ToOne<>(this,
            SensorValue_.sensor_timeseries);

    public SensorValue(long timestamp, List<StringEntitiy> values ) {
        this.timestamp = timestamp;
        this.values = values;
    }

    @Generated(1281615673)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public SensorValue(long timestamp, long sensor_timeseriesId) {
        this.timestamp = timestamp;
        this.sensor_timeseriesToOne.setTargetId(sensor_timeseriesId);
    }

    @Generated(1511460590)
    public SensorValue() {
    }

    public void addValue(StringEntitiy value)
    {
        values.add(value);
    }

    public long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }

    /** To-one relationship, resolved on first access. */
    @Generated(816761306)
    public SensorTimeseries getSensor_timeseries() {
        sensor_timeseries = sensor_timeseriesToOne.getTarget();
        return sensor_timeseries;
    }

    /** Set the to-one relation including its ID property. */
    @Generated(464093738)
    public void setSensor_timeseries(SensorTimeseries sensor_timeseries) {
        sensor_timeseriesToOne.setTarget(sensor_timeseries);
        this.sensor_timeseries = sensor_timeseries;
    }

    public List<StringEntitiy> getValues() {
        return values;
    }
}
