package de.dennis.mobilesensing_module.mobilesensing.Storage;

import java.util.List;

import io.objectbox.annotation.Backlink;
import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.Index;
import io.objectbox.annotation.Relation;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.relation.ToOne;
import io.objectbox.BoxStore;
import io.objectbox.relation.ToMany;


/**
 * Created by Dennis on 12.07.2017.
 */
@Entity
public class SensorTimeseries {


    @Id(assignable = true)
    private long timestamp;

    @Index
    private String timestamp_day;

    private String type;
    private String sensor_id;
    private String user;

    @Relation
    SensorInfo sensor_info;

    @Backlink
    private List<SensorValue> values = new ToMany<>(this, SensorTimeseries_.values);

    /** Used to resolve relations */
    @Internal
    @Generated(1307364262)
    transient BoxStore __boxStore;

    @Internal
    @Generated(1965469809)
    transient ToOne<SensorInfo> sensor_infoToOne = new ToOne<>(this, SensorTimeseries_.sensor_info);

    public SensorTimeseries(long timestamp, String timestamp_day, String type, String sensor_id, String user,
                            SensorInfo sensor_info, List<SensorValue> values) {
        this.timestamp = timestamp;
        this.timestamp_day = timestamp_day;
        this.type = type;
        this. sensor_id = sensor_id;
        this.user = user;
        this.sensor_info = sensor_info;
        this.values = values;
    }

    @Generated(1451199262)
    public SensorTimeseries() {
    }

    @Generated(2090206812)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public SensorTimeseries(long timestamp, String timestamp_day, String type, String sensor_id, String user,
            long sensor_infoId) {
        this.timestamp = timestamp;
        this.timestamp_day = timestamp_day;
        this.type = type;
        this.sensor_id = sensor_id;
        this.user = user;
        this.sensor_infoToOne.setTargetId(sensor_infoId);
    }

    public String getTimestamp_day() {
        return timestamp_day;
    }

    public void setTimestamp_day(String timestamp_day) {
        this.timestamp_day = timestamp_day;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getSensor_id() {
        return sensor_id;
    }

    public void setSensor_id(String sensor_id) {
        this.sensor_id = sensor_id;
    }

    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }

    public List<SensorValue> getValues() {
        return values;
    }

    public void setValues(List<SensorValue> values) {
        this.values = values;
    }

    public BoxStore get__boxStore() {
        return __boxStore;
    }

    public void set__boxStore(BoxStore __boxStore) {
        this.__boxStore = __boxStore;
    }

    /** To-one relationship, resolved on first access. */
    @Generated(174470659)
    public SensorInfo getSensor_info() {
        sensor_info = sensor_infoToOne.getTarget();
        return sensor_info;
    }

    /** Set the to-one relation including its ID property. */
    @Generated(744333247)
    public void setSensor_info(SensorInfo sensor_info) {
        sensor_infoToOne.setTarget(sensor_info);
        this.sensor_info = sensor_info;
    }

    public ToOne<SensorInfo> getSensor_infoToOne() {
        return sensor_infoToOne;
    }

    public void setSensor_infoToOne(ToOne<SensorInfo> sensor_infoToOne) {
        this.sensor_infoToOne = sensor_infoToOne;
    }
}
