package de.dennis.mobilesensing_module.mobilesensing.Storage;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import io.objectbox.annotation.Backlink;
import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Relation;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.BoxStore;
import io.objectbox.relation.ToMany;
import io.objectbox.relation.ToOne;

/**
 * Created by Dennis on 04.08.2017.
 */
@Entity
public class SensorInfo {

    @Id
    private long id;

    private String sensor_name;
    private String description;

    @Backlink
    private List<ValueInfo> value_info = new ToMany<>(this, SensorInfo_.value_info);

    /** Used to resolve relations */
    @Internal
    @Generated(1307364262)
    transient BoxStore __boxStore;

    public SensorInfo(String sensor_name, String description, List<ValueInfo> value_info) {
        id = 0;
        this.sensor_name = sensor_name;
        this.description = description;
        this.value_info = value_info;
    }

    @Generated(1004933406)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public SensorInfo(long id, String sensor_name, String description) {
        this.id = id;
        this.sensor_name = sensor_name;
        this.description = description;
    }

    @Generated(1592317574)
    public SensorInfo() {
    }

    public String getSensor_name() {
        return sensor_name;
    }

    public String getDescription() {
        return description;
    }

    public List<ValueInfo> getValue_info() {
        return value_info;
    }

    public void addValue_info(ValueInfo info) {
       value_info.add(info);
    }

    public long getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public void setSensor_name(String sensor_name) {
        this.sensor_name = sensor_name;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setId(long id) {
        this.id = id;
    }

    public void setValue_info(List<ValueInfo> value_info) {
        this.value_info = value_info;
    }

    public BoxStore get__boxStore() {
        return __boxStore;
    }

    public void set__boxStore(BoxStore __boxStore) {
        this.__boxStore = __boxStore;
    }
}
