package de.dennis.mobilesensing_module.mobilesensing.Storage;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Relation;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.BoxStore;
import io.objectbox.relation.ToOne;

/**
 * Created by Dennis on 04.08.2017.
 */
@Entity
public class StringEntitiy {
    @Id
    private long id;

    private String value;
    @Relation
    private SensorValue sensor_value;

    /** Used to resolve relations */
    @Internal
    @Generated(1307364262)
    transient BoxStore __boxStore;

    @Internal
    @Generated(1734713596)
    transient ToOne<SensorValue> sensor_valueToOne = new ToOne<>(this,
            StringEntitiy_.sensor_value);

    public StringEntitiy(String value) {
        this.value = value;
    }

    @Generated(1956950100)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public StringEntitiy(long id, String value, long sensor_valueId) {
        this.id = id;
        this.value = value;
        this.sensor_valueToOne.setTargetId(sensor_valueId);
    }

    @Generated(2091734891)
    public StringEntitiy() {
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    /** To-one relationship, resolved on first access. */
    @Generated(150948073)
    public SensorValue getSensor_value() {
        sensor_value = sensor_valueToOne.getTarget();
        return sensor_value;
    }

    /** Set the to-one relation including its ID property. */
    @Generated(160285928)
    public void setSensor_value(SensorValue sensor_value) {
        sensor_valueToOne.setTarget(sensor_value);
        this.sensor_value = sensor_value;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }
}
