package de.dennis.mobilesensing_module.mobilesensing.Storage;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Relation;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.BoxStore;
import io.objectbox.relation.ToOne;

/**
 * Created by Dennis on 04.08.2017.
 */

@Entity
public class ValueInfo {

    @Id
    private long id;

    private String name;
    private String description;
    private String unit;

    @Relation
    private SensorInfo sensor_info;

    /** Used to resolve relations */
    @Internal
    @Generated(1307364262)
    transient BoxStore __boxStore;

    @Internal
    @Generated(2137864978)
    transient ToOne<SensorInfo> sensor_infoToOne = new ToOne<>(this,
            ValueInfo_.sensor_info);

    public ValueInfo(String name, String description, String unit) {
        this.name = name;
        this.description = description;
        this.unit = unit;
    }

    @Generated(1202527945)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public ValueInfo(long id, String name, String description, String unit,
            long sensor_infoId) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.unit = unit;
        this.sensor_infoToOne.setTargetId(sensor_infoId);
    }

    @Generated(2032455582)
    public ValueInfo() {
    }

    public String getName() {
        return name;
    }

    public String getDescription() {
        return description;
    }

    public String getUnit() {
        return unit;
    }

    public long getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    /** To-one relationship, resolved on first access. */
    @Generated(174470659)
    public SensorInfo getSensor_info() {
        sensor_info = sensor_infoToOne.getTarget();
        return sensor_info;
    }

    /** Set the to-one relation including its ID property. */
    @Generated(744333247)
    public void setSensor_info(SensorInfo sensor_info) {
        sensor_infoToOne.setTarget(sensor_info);
        this.sensor_info = sensor_info;
    }

    public void setId(long id) {
        this.id = id;
    }
}
