package de.dennis.mobilesensing_module.mobilesensing.Storage.ObjectBox.ActivityListener;

import de.dennis.mobilesensing_module.mobilesensing.Storage.ObjectBox.SensorObject;
import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Relation;
import io.objectbox.relation.ToOne;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.BoxStore;

/**
 * Created by Dennis on 01.10.2017.
 */
@Entity
public class ActivityObject extends SensorObject {
    @Id(assignable = true)
    protected long timestamp;
    protected String Activity;

    protected ToOne<ActivityTimeseries> activityTimeseries = new ToOne<>(this, ActivityObject_.activityTimeseries);
    /** Used to resolve relations */
    @Internal
    @Generated(1307364262)
    transient BoxStore __boxStore;

    public ActivityObject(long timestamp, String activity) {
        this.timestamp = timestamp;
        Activity = activity;
    }

    @Generated(437726919)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public ActivityObject(long timestamp, String Activity, long activityTimeseriesId) {
        this.timestamp = timestamp;
        this.Activity = Activity;
        this.activityTimeseries.setTargetId(activityTimeseriesId);
    }

    @Generated(451465978)
    public ActivityObject() {
    }

    public long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }

    public String getActivity() {
        return Activity;
    }

    public void setActivity(String activity) {
        Activity = activity;
    }

    public ToOne<ActivityTimeseries> getActivityTimeseries() {
        return activityTimeseries;
    }

    public void setActivityTimeseries(ToOne<ActivityTimeseries> activityTimeseries) {
        this.activityTimeseries = activityTimeseries;
    }
}
