package de.dennis.mobilesensing_module.mobilesensing.Storage.ObjectBox.GLocationListener;

import de.dennis.mobilesensing_module.mobilesensing.Storage.ObjectBox.SensorObject;
import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Relation;
import io.objectbox.relation.ToOne;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.BoxStore;

/**
 * Created by Dennis on 01.10.2017.
 */
@Entity
public class GLocationsObject extends SensorObject {
    @Id(assignable = true)
    protected long timestamp;
    protected double lat;
    protected double lng;

    protected ToOne<GLocationTimeseries> gLocationTimeseries = new ToOne<>(this, GLocationsObject_.gLocationTimeseries);
    /** Used to resolve relations */
    @Internal
    @Generated(1307364262)
    transient BoxStore __boxStore;

    public GLocationsObject(long timestamp, double lat, double lng) {
        this.timestamp = timestamp;
        this.lat = lat;
        this.lng = lng;
    }

    @Generated(1746051764)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public GLocationsObject(long timestamp, double lat, double lng, long gLocationTimeseriesId) {
        this.timestamp = timestamp;
        this.lat = lat;
        this.lng = lng;
        this.gLocationTimeseries.setTargetId(gLocationTimeseriesId);
    }

    @Generated(925336624)
    public GLocationsObject() {
    }

    public long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }

    public double getLat() {
        return lat;
    }

    public void setLat(double lat) {
        this.lat = lat;
    }

    public double getLng() {
        return lng;
    }

    public void setLng(double lng) {
        this.lng = lng;
    }

    public ToOne<GLocationTimeseries> getgLocationTimeseries() {
        return gLocationTimeseries;
    }

    public void setgLocationTimeseries(ToOne<GLocationTimeseries> gLocationTimeseries) {
        this.gLocationTimeseries = gLocationTimeseries;
    }
}
