package de.dennis.mobilesensing_module.mobilesensing.Storage.ObjectBox;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import de.dennis.mobilesensing_module.mobilesensing.Storage.ObjectBox.SensorValue;
import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Relation;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.BoxStore;
import io.objectbox.relation.ToOne;

/**
 * Created by Dennis on 25.08.2017.
 */
@Entity
public class GeoPointEntity{
    @Id
    private long id;

    private double lat;
    private double lng;

    private int sortIndex;

    @Relation
    private SensorValue sensor_value;

    /** Used to resolve relations */
    @Internal
    @Generated(1307364262)
    transient BoxStore __boxStore;

    @Internal
    @Generated(1490258748)
    transient ToOne<SensorValue> sensor_valueToOne = new ToOne<>(this,
            GeoPointEntity_.sensor_value);

    //Constructor
    public GeoPointEntity(double lat, double lng){
        this.lat = lat;
        this.lng = lng;
    }

    @Generated(1199347633)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public GeoPointEntity(long id, double lat, double lng, int sortIndex,
            long sensor_valueId) {
        this.id = id;
        this.lat = lat;
        this.lng = lng;
        this.sortIndex = sortIndex;
        this.sensor_valueToOne.setTargetId(sensor_valueId);
    }

    @Generated(2068737748)
    public GeoPointEntity() {
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public double getLat() {
        return lat;
    }

    public void setLat(float lat) {
        this.lat = lat;
    }

    public double getLng() {
        return lng;
    }

    public void setLng(float lng) {
        this.lng = lng;
    }

    public int getSortIndex() {
        return sortIndex;
    }

    public void setSortIndex(int sortIndex) {
        this.sortIndex = sortIndex;
    }

    /** To-one relationship, resolved on first access. */
    @Generated(150948073)
    public SensorValue getSensor_value() {
        sensor_value = sensor_valueToOne.getTarget();
        return sensor_value;
    }

    /** Set the to-one relation including its ID property. */
    @Generated(160285928)
    public void setSensor_value(SensorValue sensor_value) {
        sensor_valueToOne.setTarget(sensor_value);
        this.sensor_value = sensor_value;
    }

    public JSONObject toJSON() throws JSONException {
        JSONObject jo = new JSONObject();
        jo.put("type","Point");
        JSONArray ja = new JSONArray();
        ja.put(getLat());
        ja.put(getLng());
        jo.put("coordinates",ja);
        return  jo;
    }

    public void setLat(double lat) {
        this.lat = lat;
    }

    public void setLng(double lng) {
        this.lng = lng;
    }
}
