package de.dennis.mobilesensing_module.mobilesensing.Storage.ObjectBox;

import de.dennis.mobilesensing_module.mobilesensing.Storage.ObjectBox.SensorValue;
import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.Relation;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.BoxStore;
import io.objectbox.relation.ToOne;

/**
 * Created by Dennis on 25.08.2017.
 */
@Entity
public class IntegerEntity{
    @Id
    private long id;
    private int value;

    private int sortIndex;

    @Relation
    private SensorValue sensor_value;
    /** Used to resolve relations */
    @Internal
    @Generated(1307364262)
    transient BoxStore __boxStore;
    @Internal
    @Generated(681698240)
    transient ToOne<SensorValue> sensor_valueToOne = new ToOne<>(this,
            IntegerEntity_.sensor_value);

    //Constructor
    public IntegerEntity (int value){
        this.value = value;
    }

    @Generated(1263979062)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public IntegerEntity(long id, int value, int sortIndex, long sensor_valueId) {
        this.id = id;
        this.value = value;
        this.sortIndex = sortIndex;
        this.sensor_valueToOne.setTargetId(sensor_valueId);
    }

    public int getSortIndex() {
        return sortIndex;
    }

    public void setSortIndex(int sortIndex) {
        this.sortIndex = sortIndex;
    }

    @Generated(1345843987)
    public IntegerEntity() {
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public int getValue() {
        return value;
    }

    public void setValue(int value) {
        this.value = value;
    }
    /** To-one relationship, resolved on first access. */
    @Generated(150948073)
    public SensorValue getSensor_value() {
        sensor_value = sensor_valueToOne.getTarget();
        return sensor_value;
    }

    /** Set the to-one relation including its ID property. */
    @Generated(160285928)
    public void setSensor_value(SensorValue sensor_value) {
        sensor_valueToOne.setTarget(sensor_value);
        this.sensor_value = sensor_value;
    }
}
