package de.dennis.mobilesensing_module.mobilesensing.Storage.ObjectBox;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.util.ArrayList;
import java.util.List;

import io.objectbox.BoxStore;
import io.objectbox.annotation.Backlink;
import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Relation;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.relation.ToOne;
import io.objectbox.relation.ToMany;

/**
 * Created by Dennis on 25.08.2017.
 */
@Entity
public class LineStringEntity {
    @Id
    private long id;

    private int sortIndex;

    @Backlink
    private List<GeoPointEntity> values = new ToMany<>(this, LineStringEntity_.values);

    @Relation
    private SensorValue sensor_value;

    /** Used to resolve relations */
    @Internal
    @Generated(1307364262)
    transient BoxStore __boxStore;

    @Internal
    @Generated(1311783093)
    transient ToOne<SensorValue> sensor_valueToOne = new ToOne<>(this,
            LineStringEntity_.sensor_value);



    @Generated(1968066359)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public LineStringEntity(long id, int sortIndex, long sensor_valueId) {
        this.id = id;
        this.sortIndex = sortIndex;
        this.sensor_valueToOne.setTargetId(sensor_valueId);
    }

    @Generated(264629804)
    public LineStringEntity() {
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public int getSortIndex() {
        return sortIndex;
    }

    public void setSortIndex(int sortIndex) {
        this.sortIndex = sortIndex;
    }

    /** To-one relationship, resolved on first access. */
    @Generated(150948073)
    public SensorValue getSensor_value() {
        sensor_value = sensor_valueToOne.getTarget();
        return sensor_value;
    }

    /** Set the to-one relation including its ID property. */
    @Generated(160285928)
    public void setSensor_value(SensorValue sensor_value) {
        sensor_valueToOne.setTarget(sensor_value);
        this.sensor_value = sensor_value;
    }

    public JSONObject toJSON() throws JSONException {
                        /*{ "type": "LineString",
                    "coordinates": [
                        [30, 10], [10, 30], [40, 40]
                        ]
                        }*/
        JSONObject jo = new JSONObject();
        jo.put("type","LineString");
        JSONArray ja = new JSONArray();
        for(GeoPointEntity gpe: values){
            JSONArray jaGP = new JSONArray();
            jaGP.put(gpe.getLat());
            jaGP.put(gpe.getLng());
            ja.put(jaGP);
        }
        jo.put("coordinates",ja);
        return  jo;
    }

    public void addGeoPoint(GeoPointEntity geoPoint){
        if(values== null){
            values = new ArrayList<>();
        }
        values.add(geoPoint);
    }

    public List<GeoPointEntity> getValues() {
        return values;
    }
}
