package de.dennis.mobilesensing_module.mobilesensing.Storage.ObjectBox;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.util.ArrayList;
import java.util.List;

import io.objectbox.annotation.Backlink;
import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Relation;
import io.objectbox.relation.ToMany;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.BoxStore;
import io.objectbox.relation.ToOne;

/**
 * Created by Dennis on 07.08.2017.
 */
@Entity
public class SensorValue {
    @Id
    private long id;

    private long timestamp;
    @Backlink
    private List<StringEntity> values = new ToMany<>(this, SensorValue_.values);
    @Relation
    private SensorTimeseries sensor_timeseries;
    /** Used to resolve relations */
    @Internal
    @Generated(1307364262)
    transient BoxStore __boxStore;
    @Generated(1291659773)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public SensorValue(long id, long timestamp, long sensor_timeseriesId) {
        this.id = id;
        this.timestamp = timestamp;
        this.sensor_timeseriesToOne.setTargetId(sensor_timeseriesId);
    }
    @Generated(1511460590)
    public SensorValue() {
    }

    public long getId() {
        return id;
    }
    public void setId(long id) {
        this.id = id;
    }
    public long getTimestamp() {
        return timestamp;
    }
    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }
    @Internal
    @Generated(1539810802)
    transient ToOne<SensorTimeseries> sensor_timeseriesToOne = new ToOne<>(this,
            SensorValue_.sensor_timeseries);
    /** To-one relationship, resolved on first access. */
    @Generated(816761306)
    public SensorTimeseries getSensor_timeseries() {
        sensor_timeseries = sensor_timeseriesToOne.getTarget();
        return sensor_timeseries;
    }
    /** Set the to-one relation including its ID property. */
    @Generated(464093738)
    public void setSensor_timeseries(SensorTimeseries sensor_timeseries) {
        sensor_timeseriesToOne.setTarget(sensor_timeseries);
        this.sensor_timeseries = sensor_timeseries;
    }

    public List<StringEntity> getValues() {
        return values;
    }

    public void setValues(List<StringEntity> values) {
        this.values = values;
    }

    public BoxStore get__boxStore() {
        return __boxStore;
    }

    public void set__boxStore(BoxStore __boxStore) {
        this.__boxStore = __boxStore;
    }

    public ToOne<SensorTimeseries> getSensor_timeseriesToOne() {
        return sensor_timeseriesToOne;
    }

    public void setSensor_timeseriesToOne(ToOne<SensorTimeseries> sensor_timeseriesToOne) {
        this.sensor_timeseriesToOne = sensor_timeseriesToOne;
    }
    //Constructor
    public SensorValue(long timestamp, List<StringEntity> values){
        this.id = 0;
        this.timestamp = timestamp;
        for(StringEntity se: values){
            se.setSensor_value(this);
        }
        setValues(values);
    }

    public SensorValue(long timestamp) {
        this.id = 0;
        this.timestamp = timestamp;
        values = new ArrayList<>();
        setValues(values);
    }

    public void addStringEntity(StringEntity se) {
        se.setSensor_value(this);
        if(values == null) {
            values = new ArrayList<>();
            setValues(values);
        }
        values.add(se);
    }

    public JSONObject toJSON() throws JSONException {
        /*
        {"timestamp":"1471352846000", "value": [0.85, 0.6, 0.5]}
         */
        JSONObject sv = new JSONObject();
        sv.put("timestamp",getTimestamp());
        JSONArray value = new JSONArray();
        for(StringEntity se: getValues()){
            value.put(se.getValue());
        }
        sv.put("value",value);
        return  sv;
    }


}
