package de.dennis.mobilesensing_module.mobilesensing.Storage.ObjectBox;

import org.json.JSONException;
import org.json.JSONObject;

import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Relation;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.BoxStore;
import io.objectbox.relation.ToOne;

/**
 * Created by Dennis on 07.08.2017.
 */
@Entity
public class ValueInfo {
    @Id
    private long id;
    private String name;
    private String description;
    private String unit;
    @Relation
    private SensorInfo sensor_info;
    /** Used to resolve relations */
    @Internal
    @Generated(1307364262)
    transient BoxStore __boxStore;
    @Generated(1202527945)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public ValueInfo(long id, String name, String description, String unit, long sensor_infoId) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.unit = unit;
        this.sensor_infoToOne.setTargetId(sensor_infoId);
    }
    @Generated(2032455582)
    public ValueInfo() {
    }
    public long getId() {
        return id;
    }
    public void setId(long id) {
        this.id = id;
    }
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return description;
    }
    public void setDescription(String description) {
        this.description = description;
    }
    public String getUnit() {
        return unit;
    }
    public void setUnit(String unit) {
        this.unit = unit;
    }
    @Internal
    @Generated(2137864978)
    transient ToOne<SensorInfo> sensor_infoToOne = new ToOne<>(this,
            ValueInfo_.sensor_info);
    /** To-one relationship, resolved on first access. */
    @Generated(174470659)
    public SensorInfo getSensor_info() {
        sensor_info = sensor_infoToOne.getTarget();
        return sensor_info;
    }
    /** Set the to-one relation including its ID property. */
    @Generated(744333247)
    public void setSensor_info(SensorInfo sensor_info) {
        sensor_infoToOne.setTarget(sensor_info);
        this.sensor_info = sensor_info;
    }

    public BoxStore get__boxStore() {
        return __boxStore;
    }

    public void set__boxStore(BoxStore __boxStore) {
        this.__boxStore = __boxStore;
    }

    public ToOne<SensorInfo> getSensor_infoToOne() {
        return sensor_infoToOne;
    }

    public void setSensor_infoToOne(ToOne<SensorInfo> sensor_infoToOne) {
        this.sensor_infoToOne = sensor_infoToOne;
    }

    //Constructor
    public ValueInfo(String name, String description, String unit){
        this.id = 0;
        this.name = name;
        this.description = description;
        this.unit = unit;
    }

    public JSONObject toJSON() throws JSONException {
        /*
        { "name": "Standing", "description": "User is standing.", "unit": "probability (float)" }
         */
        JSONObject vi = new JSONObject();
        vi.put("name", getName());
        vi.put("description",getDescription());
        vi.put("unit",getUnit());
        return vi;
    }
}
