package de.dennis.mobilesensing_module.mobilesensing.Storage.ObjectBox.GLocation;

import de.dennis.mobilesensing_module.mobilesensing.Storage.ObjectBox.SensorObject;
import de.dennis.mobilesensing_module.mobilesensing.Storage.ObjectBox.SensorTimeseries;
import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Index;
import io.objectbox.annotation.Transient;
import io.objectbox.relation.ToOne;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.BoxStore;

/**
 * Created by Dennis on 01.10.2017.
 */
@Entity
public class GLocationsObject extends SensorObject {
    @Id
    public long id;
    @Index
    public long timestamp;
    public double lat;
    public double lng;
    public float speed;
    public boolean isClustered;
    @Index
    public long parentCluster;

    public ToOne<GLocationTimeseries> gLocationTimeseries;
    /** Used to resolve relations */
    @Internal
    @Generated(1307364262)
    transient BoxStore __boxStore;

    public GLocationsObject(long id, long timestamp, double lat, double lng, float speed, long parentCluster) {
        this.id = id;
        this.timestamp = timestamp;
        this.lat = lat;
        this.lng = lng;
        this.isClustered = false;
        this.speed = speed;
        this.parentCluster = parentCluster;
    }

    public GLocationsObject(long timestamp, double lat, double lng, float speed) {
        this.timestamp = timestamp;
        this.lat = lat;
        this.lng = lng;
        this.isClustered = false;
        this.speed = speed;
        this.parentCluster = 0L;
    }
    @Generated(1746051764)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public GLocationsObject(long timestamp, double lat, double lng, long gLocationTimeseriesId) {
        this.timestamp = timestamp;
        this.lat = lat;
        this.lng = lng;
        this.gLocationTimeseries.setTargetId(gLocationTimeseriesId);
    }

    @Generated(925336624)
    public GLocationsObject() {
    }

    public long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }

    public double getLat() {
        return lat;
    }

    public void setLat(double lat) {
        this.lat = lat;
    }

    public double getLng() {
        return lng;
    }

    public void setLng(double lng) {
        this.lng = lng;
    }

    public ToOne<GLocationTimeseries> getgLocationTimeseries() {
        return gLocationTimeseries;
    }

    public void setgLocationTimeseries(ToOne<GLocationTimeseries> gLocationTimeseries) {
        this.gLocationTimeseries = gLocationTimeseries;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }
}
