package de.dennis.mobilesensing_module.mobilesensing.Storage.ObjectBox.ScreenOnListener;

import de.dennis.mobilesensing_module.mobilesensing.Storage.ObjectBox.RunningApplicationListener.RunningApplicationTimeseries;
import de.dennis.mobilesensing_module.mobilesensing.Storage.ObjectBox.SensorObject;
import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Relation;
import io.objectbox.relation.ToOne;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.BoxStore;

/**
 * Created by Dennis on 01.10.2017.
 */
@Entity
public class ScreenOnObject extends SensorObject {
    @Id(assignable = true)
    protected long timestamp;
    protected boolean screenOn;

    protected ToOne<ScreenOnTimeseries> screenOnTimeseries = new ToOne<>(this, ScreenOnObject_.screenOnTimeseries);
    /** Used to resolve relations */
    @Internal
    @Generated(1307364262)
    transient BoxStore __boxStore;

    public ScreenOnObject(long timestamp, boolean screenOn) {
        this.timestamp = timestamp;
        this.screenOn = screenOn;
    }

    @Generated(905272543)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public ScreenOnObject(long timestamp, boolean screenOn, long screenOnTimeseriesId) {
        this.timestamp = timestamp;
        this.screenOn = screenOn;
        this.screenOnTimeseries.setTargetId(screenOnTimeseriesId);
    }

    @Generated(742735190)
    public ScreenOnObject() {
    }

    public long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }

    public boolean isScreenOn() {
        return screenOn;
    }

    public void setScreenOn(boolean screenOn) {
        this.screenOn = screenOn;
    }

    public void setScreenOnTimeseries(ToOne<ScreenOnTimeseries> screenOnTimeseries) {
        this.screenOnTimeseries = screenOnTimeseries;
    }

    public ToOne<ScreenOnTimeseries> getScreenOnTimeseries() {
        return screenOnTimeseries;
    }

    public boolean getScreenOn() {
        return screenOn;
    }
}
