package de.dennis.mobilesensing_module.mobilesensing.Storage.ObjectBox.RunningApplicationListener;

import de.dennis.mobilesensing_module.mobilesensing.Storage.ObjectBox.GLocationListener.GLocationTimeseries;
import de.dennis.mobilesensing_module.mobilesensing.Storage.ObjectBox.SensorObject;
import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Relation;
import io.objectbox.relation.ToOne;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.BoxStore;

/**
 * Created by Dennis on 01.10.2017.
 */
@Entity
public class RunningApplicationObject extends SensorObject {
    @Id(assignable = true)
    protected long timestamp;
    protected String applicationName;

    protected ToOne<RunningApplicationTimeseries> runningApplicationTimeseries = new ToOne<>(this, RunningApplicationObject_.runningApplicationTimeseries);
    /** Used to resolve relations */
    @Internal
    @Generated(1307364262)
    transient BoxStore __boxStore;

    public RunningApplicationObject(long timestamp, String applicationName) {
        this.timestamp = timestamp;
        this.applicationName = applicationName;
    }

    @Generated(1957867338)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public RunningApplicationObject(long timestamp, String applicationName, long runningApplicationTimeseriesId) {
        this.timestamp = timestamp;
        this.applicationName = applicationName;
        this.runningApplicationTimeseries.setTargetId(runningApplicationTimeseriesId);
    }

    @Generated(250921469)
    public RunningApplicationObject() {
    }

    public long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }

    public String getApplicationName() {
        return applicationName;
    }

    public void setApplicationName(String applicationName) {
        this.applicationName = applicationName;
    }

    public ToOne<RunningApplicationTimeseries> getRunningApplicationTimeseries() {
        return runningApplicationTimeseries;
    }

    public void setRunningApplicationTimeseries(ToOne<RunningApplicationTimeseries> runningApplicationTimeseries) {
        this.runningApplicationTimeseries = runningApplicationTimeseries;
    }
}
