package de.dennis.mobilesensing_module.mobilesensing.Storage.ObjectBox.NetworkListener;

import de.dennis.mobilesensing_module.mobilesensing.Storage.ObjectBox.GLocationListener.GLocationTimeseries;
import de.dennis.mobilesensing_module.mobilesensing.Storage.ObjectBox.SensorObject;
import io.objectbox.annotation.Backlink;
import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Index;
import io.objectbox.annotation.Relation;
import io.objectbox.relation.ToOne;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.BoxStore;

/**
 * Created by Dennis on 01.10.2017.
 */
@Entity
public class NetworkObject extends SensorObject {
    @Id
    public long id;
    @Index
    public long timestamp;
    public String networkType;

    public ToOne<NetworkTimeseries> networkTimeseries;
    /** Used to resolve relations */
    @Internal
    @Generated(1307364262)
    transient BoxStore __boxStore;

    public NetworkObject(long timestamp, String networkType) {
        this.timestamp = timestamp;
        this.networkType = networkType;
    }

    @Generated(1181843410)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public NetworkObject(long timestamp, String networkType, long networkTimeseriesId) {
        this.timestamp = timestamp;
        this.networkType = networkType;
        this.networkTimeseries.setTargetId(networkTimeseriesId);
    }

    @Generated(1884029187)
    public NetworkObject() {
    }

    public long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }

    public String getNetworkType() {
        return networkType;
    }

    public void setNetworkType(String networkType) {
        this.networkType = networkType;
    }

    public ToOne<NetworkTimeseries> getNetworkTimeseries() {
        return networkTimeseries;
    }

    public void setNetworkTimeseries(ToOne<NetworkTimeseries> networkTimeseries) {
        this.networkTimeseries = networkTimeseries;
    }
}
