package de.dennis.mobilesensing_module.mobilesensing.Storage.ObjectBox.NetworkListener;

import java.util.ArrayList;
import java.util.GregorianCalendar;
import java.util.List;

import de.dennis.mobilesensing_module.mobilesensing.Storage.ObjectBox.GLocationListener.GLocationsObject;
import de.dennis.mobilesensing_module.mobilesensing.Storage.ObjectBox.SensorTimeseries;
import io.objectbox.annotation.Backlink;
import io.objectbox.annotation.Entity;
import io.objectbox.annotation.Id;
import io.objectbox.annotation.Index;
import io.objectbox.relation.ToMany;
import io.objectbox.annotation.Generated;
import io.objectbox.annotation.apihint.Internal;
import io.objectbox.BoxStore;

/**
 * Created by Dennis on 01.10.2017.
 */
@Entity
public class NetworkTimeseries extends SensorTimeseries {
    @Id(assignable = true)
    protected long timestamp;
    @Index
    protected String timestamp_day;
    protected boolean uploaded;
    @Backlink
    protected ToMany<NetworkObject> values = new ToMany<>(this, NetworkTimeseries_.values);
    /** Used to resolve relations */
    @Internal
    @Generated(1307364262)
    transient BoxStore __boxStore;

    public NetworkTimeseries(long timestamp) {
        this.timestamp = timestamp;
        GregorianCalendar g = new GregorianCalendar();
        g.setTimeInMillis(timestamp);
        timestamp_day = g.get(GregorianCalendar.YEAR)+"-"+g.get(GregorianCalendar.MONTH)+"-"+g.get(GregorianCalendar.DAY_OF_MONTH)+"T"+"00:00:00.000Z";
        uploaded = false;
    }

    @Generated(357367493)
    @Internal
    /** This constructor was generated by ObjectBox and may change any time. */
    public NetworkTimeseries(long timestamp, String timestamp_day, boolean uploaded) {
        this.timestamp = timestamp;
        this.timestamp_day = timestamp_day;
        this.uploaded = uploaded;
    }

    @Generated(725512538)
    public NetworkTimeseries() {
    }

    public String getTimestamp_day() {
        return timestamp_day;
    }

    public void setTimestamp_day(String timestamp_day) {
        this.timestamp_day = timestamp_day;
    }

    public long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }

    public boolean isUploaded() {
        return uploaded;
    }

    public void setUploaded(boolean uploaded) {
        this.uploaded = uploaded;
    }

    public ToMany<NetworkObject> getValues() {
        return values;
    }

    public void setValues(ToMany<NetworkObject> values) {
        this.values = values;
    }

    public boolean getUploaded() {
        return uploaded;
    }
}
